services:
  # --- 1. Base de Données (Postgres) ---
  postgres:
    image: postgres:16-alpine
    container_name: c15tour-db
    environment:
      POSTGRES_DB: c15tourdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - c15-network

  # --- 2. Interface Admin BDD (PgAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: c15tour-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@c15tour.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - c15-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # --- 3. Backend (Spring Boot) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: c15tour-backend
    ports:
      - "8080:8080" # API accessible sur localhost:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/c15tourdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpassword
      # Autoriser les appels venant du frontend
      ALLOWED_ORIGINS: "http://localhost,http://localhost:5173"
    depends_on:
      - postgres
    networks:
      - c15-network

  # --- 4. Frontend (React + Vite) ---
  frontend:
    build:
      context: ../c15-tour-webapp
      dockerfile: Dockerfile
    container_name: c15tour-frontend
    ports:
      - "80:80" # Site accessible sur http://localhost
    depends_on:
      - backend
    networks:
      - c15-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  c15-network:
    driver: bridge
