ALTER TABLE tours ADD COLUMN IF NOT EXISTS organiser_code VARCHAR(6) UNIQUE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS organiser_joined BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS organiser_session_token VARCHAR(255) UNIQUE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS organiser_lat DOUBLE PRECISION;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS organiser_lng DOUBLE PRECISION;
