openapi: 3.0.3
info:
  title: C15Tour API
  version: 0.0.1
  description: API minimale pour initialisation.

paths:
  /ping:
    get:
      summary: Health Check
      operationId: ping
      tags:
        - System
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /tours:
    post:
      summary: Create a new tour
      operationId: createTour
      tags:
        - Tours
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TourResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get all tours
      operationId: getAllTours
      tags:
        - Tours
      responses:
        '200':
          description: List of tours
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TourResponse'
  /tours/{id}:
    get:
      summary: Get a tour by ID
      operationId: getTourById
      tags:
        - Tours
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Tour found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TourResponse'
        '404':
          description: Tour not found

    put:
      summary: Update a tour by ID
      operationId: updateTour
      tags:
        - Tours
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TourCreateRequest'
      responses:
        '200':
          description: Tour updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TourResponse'
        '404':
          description: Tour not found'

    delete:
      summary: Delete a tour by ID
      operationId: deleteTour
      tags:
        - Tours
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Tour deleted
        '404':
          description: Tour not found

components:
  schemas:
    Coordinates:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: double
          example: 47.218371
        longitude:
          type: number
          format: double
          example: -1.553621

    Message:
      type: object
      properties:
        content:
          type: string
          example: "Pong"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "Invalid input data"

    TourCreateRequest:
      type: object
      required:
        - name
        - startPoint
        - endPoint
      properties:
        name:
          type: string
          example: "Roadtrip Nantes"
        startPoint:
          $ref: '#/components/schemas/Coordinates'
        endPoint:
          $ref: '#/components/schemas/Coordinates'
        waypoints:
          type: array
          description: "List of intermediate stops"
          items:
            $ref: '#/components/schemas/Coordinates'

    TourResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Roadtrip Nantes"
        startPoint:
          $ref: '#/components/schemas/Coordinates'
        endPoint:
          $ref: '#/components/schemas/Coordinates'
        waypoints:
            type: array
            items:
                $ref: '#/components/schemas/Coordinates'
